services:  
  - type: web
    name: belacardapios-api
    runtime: node
    repo: https://github.com/ribeiroevandro/bela-cardapios-api
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.1.0
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
